from __future__ import annotations

from .codes import (
    LOOKUP_ACCURACY_OF_COORDINATES,
    LOOKUP_ACCURACY_OF_DATE,
    LOOKUP_ACCURACY_PULLUS_AGE,
    LOOKUP_BILL_METHOD,
    LOOKUP_BROOD_PATCH,
    LOOKUP_CARPAL_COVERT,
    LOOKUP_CATCHING_LURES,
    LOOKUP_CATCHING_METHOD,
    LOOKUP_CIRCUMSTANCES,
    LOOKUP_CIRCUMSTANCES_PRESUMED,
    LOOKUP_CONDITION,
    LOOKUP_EURING_CODE_IDENTIFIER,
    LOOKUP_FAT_SCORE_METHOD,
    LOOKUP_MANIPULATED,
    LOOKUP_METAL_RING_INFORMATION,
    LOOKUP_MOULT,
    LOOKUP_MOVED_BEFORE_ENCOUNTER,
    LOOKUP_PECTORAL_MUSCLE_SCORE,
    LOOKUP_PLUMAGE_CODE,
    LOOKUP_PRIMARY_IDENTIFICATION_METHOD,
    LOOKUP_SEX,
    LOOKUP_SEXING_METHOD,
    LOOKUP_STATE_OF_WING_POINT,
    LOOKUP_STATUS,
    LOOKUP_TARSUS_METHOD,
    LOOKUP_VERIFICATION_OF_THE_METAL_RING,
    lookup_age,
    lookup_brood_size,
    lookup_date,
    lookup_geographical_coordinates,
    lookup_other_marks,
    lookup_place_code,
    lookup_pullus_age,
    lookup_ring_number,
    lookup_ringing_scheme,
    lookup_species,
    parse_direction,
    parse_geographical_coordinates,
    parse_latitude,
    parse_longitude,
    parse_old_greater_coverts,
    parse_place_code,
)
from .field_schema import EuringField, EuringFormattedField, EuringLookupField
from .types import (
    TYPE_ALPHABETIC,
    TYPE_ALPHANUMERIC,
    TYPE_INTEGER,
    TYPE_NUMERIC,
    TYPE_NUMERIC_SIGNED,
    TYPE_TEXT,
)

SPEC_MANUAL = "EURING Exchange Code 2020 v202 (13 Nov 2024)"

# Schema list (definitions), not per-record data.

EURING_FIELDS = [
    EuringLookupField(
        name="Ringing Scheme",
        key="ringing_scheme",
        type_name=TYPE_ALPHABETIC,
        length=3,
        lookup=lookup_ringing_scheme,
    ),
    EuringLookupField(
        name="Primary Identification Method",
        key="primary_identification_method",
        type_name=TYPE_ALPHANUMERIC,
        length=2,
        lookup=LOOKUP_PRIMARY_IDENTIFICATION_METHOD,
    ),
    EuringLookupField(
        name="Identification Number (ring)",
        key="identification_number",
        type_name=TYPE_ALPHANUMERIC,
        length=10,
        lookup=lookup_ring_number,
    ),
    EuringLookupField(
        name="Verification of the Metal Ring",
        key="verification_of_the_metal_ring",
        type_name=TYPE_INTEGER,
        length=1,
        lookup=LOOKUP_VERIFICATION_OF_THE_METAL_RING,
    ),
    EuringLookupField(
        name="Metal Ring Information",
        key="metal_ring_information",
        type_name=TYPE_INTEGER,
        length=1,
        lookup=LOOKUP_METAL_RING_INFORMATION,
    ),
    EuringLookupField(
        name="Other Marks Information",
        key="other_marks_information",
        type_name=TYPE_ALPHABETIC,
        length=2,
        lookup=lookup_other_marks,
    ),
    EuringLookupField(
        name="Species Mentioned",
        key="species_mentioned",
        type_name=TYPE_INTEGER,
        length=5,
        lookup=lookup_species,
    ),
    EuringLookupField(
        name="Species Concluded",
        key="species_concluded",
        type_name=TYPE_INTEGER,
        length=5,
        lookup=lookup_species,
    ),
    EuringLookupField(
        name="Manipulated",
        key="manipulated",
        type_name=TYPE_ALPHABETIC,
        length=1,
        lookup=LOOKUP_MANIPULATED,
    ),
    EuringLookupField(
        name="Moved Before Encounter",
        key="moved_before_recovery",
        type_name=TYPE_INTEGER,
        length=1,
        lookup=LOOKUP_MOVED_BEFORE_ENCOUNTER,
    ),
    EuringLookupField(
        name="Catching Method",
        key="catching_method",
        type_name=TYPE_ALPHABETIC,
        length=1,
        lookup=LOOKUP_CATCHING_METHOD,
    ),
    EuringLookupField(
        name="Catching Lures",
        key="catching_lures",
        type_name=TYPE_ALPHABETIC,
        length=1,
        lookup=LOOKUP_CATCHING_LURES,
    ),
    EuringLookupField(
        name="Sex Mentioned", key="sex_mentioned", type_name=TYPE_ALPHABETIC, length=1, lookup=LOOKUP_SEX
    ),
    EuringLookupField(
        name="Sex Concluded", key="sex_concluded", type_name=TYPE_ALPHABETIC, length=1, lookup=LOOKUP_SEX
    ),
    EuringLookupField(
        name="Age Mentioned", key="age_mentioned", type_name=TYPE_ALPHANUMERIC, length=1, lookup=lookup_age
    ),
    EuringLookupField(
        name="Age Concluded", key="age_concluded", type_name=TYPE_ALPHANUMERIC, length=1, lookup=lookup_age
    ),
    EuringLookupField(name="Status", key="status", type_name=TYPE_ALPHABETIC, length=1, lookup=LOOKUP_STATUS),
    EuringLookupField(name="Brood Size", key="brood_size", type_name=TYPE_INTEGER, length=2, lookup=lookup_brood_size),
    EuringLookupField(name="Pullus Age", key="pullus_age", type_name=TYPE_INTEGER, length=2, lookup=lookup_pullus_age),
    EuringLookupField(
        name="Accuracy of Pullus Age",
        key="accuracy_of_pullus_age",
        type_name=TYPE_ALPHANUMERIC,
        length=1,
        lookup=LOOKUP_ACCURACY_PULLUS_AGE,
    ),
    EuringLookupField(name="Date", key="date", type_name=TYPE_INTEGER, length=8, lookup=lookup_date),
    EuringLookupField(
        name="Accuracy of Date",
        key="accuracy_of_date",
        type_name=TYPE_INTEGER,
        length=1,
        lookup=LOOKUP_ACCURACY_OF_DATE,
    ),
    EuringField(name="Time", key="time", type_name=TYPE_ALPHANUMERIC, length=4),
    EuringFormattedField(
        name="Place Code",
        key="place_code",
        type_name=TYPE_ALPHANUMERIC,
        length=4,
        parser=parse_place_code,
        lookup=lookup_place_code,
    ),
    EuringFormattedField(
        name="Geographical Co-ordinates",
        key="geographical_coordinates",
        type_name=TYPE_ALPHANUMERIC,
        length=15,
        parser=parse_geographical_coordinates,
        lookup=lookup_geographical_coordinates,
    ),
    EuringLookupField(
        name="Accuracy of Co-ordinates",
        key="accuracy_of_coordinates",
        type_name=TYPE_ALPHANUMERIC,
        length=1,
        lookup=LOOKUP_ACCURACY_OF_COORDINATES,
    ),
    EuringLookupField(name="Condition", key="condition", type_name=TYPE_INTEGER, length=1, lookup=LOOKUP_CONDITION),
    EuringLookupField(
        name="Circumstances", key="circumstances", type_name=TYPE_INTEGER, length=2, lookup=LOOKUP_CIRCUMSTANCES
    ),
    EuringLookupField(
        name="Circumstances Presumed",
        key="circumstances_presumed",
        type_name=TYPE_INTEGER,
        length=1,
        lookup=LOOKUP_CIRCUMSTANCES_PRESUMED,
    ),
    EuringLookupField(
        name="EURING Code Identifier",
        key="euring_code_identifier",
        type_name=TYPE_INTEGER,
        length=1,
        lookup=LOOKUP_EURING_CODE_IDENTIFIER,
    ),
    EuringField(
        name="Distance",
        key="distance",
        type_name=TYPE_INTEGER,
        length=5,
        variable_length=True,
        empty_value="-----",
    ),
    EuringFormattedField(
        name="Direction",
        key="direction",
        type_name=TYPE_INTEGER,
        length=3,
        empty_value="---",
        parser=parse_direction,
    ),
    EuringField(
        name="Elapsed Time",
        key="elapsed_time",
        type_name=TYPE_INTEGER,
        length=5,
        variable_length=True,
        empty_value="-----",
    ),
    # Starting with Wing Length, fields are no longer required. Source: EURING Exchange Code 2020 v202 (13 Nov 2024).
    EuringField(name="Wing Length", key="wing_length", type_name=TYPE_NUMERIC, required=False),
    EuringField(name="Third Primary", key="third_primary", type_name=TYPE_NUMERIC, required=False),
    EuringLookupField(
        name="State of Wing Point",
        key="state_of_wing_point",
        type_name=TYPE_ALPHABETIC,
        length=1,
        required=False,
        lookup=LOOKUP_STATE_OF_WING_POINT,
    ),
    EuringField(name="Mass", key="mass", type_name=TYPE_NUMERIC, required=False),
    EuringLookupField(
        name="Moult",
        key="moult",
        type_name=TYPE_ALPHABETIC,
        length=1,
        required=False,
        lookup=LOOKUP_MOULT,
    ),
    EuringLookupField(
        name="Plumage Code",
        key="plumage_code",
        type_name=TYPE_ALPHANUMERIC,
        length=1,
        required=False,
        lookup=LOOKUP_PLUMAGE_CODE,
    ),
    EuringField(name="Hind Claw", key="hind_claw", type_name=TYPE_NUMERIC, required=False),
    EuringField(name="Bill Length", key="bill_length", type_name=TYPE_NUMERIC, required=False),
    EuringLookupField(
        name="Bill Method",
        key="bill_method",
        type_name=TYPE_ALPHABETIC,
        length=1,
        required=False,
        lookup=LOOKUP_BILL_METHOD,
    ),
    EuringField(name="Total Head Length", key="total_head_length", type_name=TYPE_NUMERIC, required=False),
    EuringField(name="Tarsus", key="tarsus", type_name=TYPE_NUMERIC, required=False),
    EuringLookupField(
        name="Tarsus Method",
        key="tarsus_method",
        type_name=TYPE_ALPHABETIC,
        length=1,
        required=False,
        lookup=LOOKUP_TARSUS_METHOD,
    ),
    EuringField(name="Tail Length", key="tail_length", type_name=TYPE_NUMERIC, required=False),
    EuringField(name="Tail Difference", key="tail_difference", type_name=TYPE_NUMERIC, required=False),
    EuringField(name="Fat Score", key="fat_score", type_name=TYPE_INTEGER, length=1, required=False),
    EuringLookupField(
        name="Fat Score Method",
        key="fat_score_method",
        type_name=TYPE_ALPHABETIC,
        length=1,
        required=False,
        lookup=LOOKUP_FAT_SCORE_METHOD,
    ),
    EuringLookupField(
        name="Pectoral Muscle Score",
        key="pectoral_muscle",
        type_name=TYPE_INTEGER,
        length=1,
        required=False,
        lookup=LOOKUP_PECTORAL_MUSCLE_SCORE,
    ),
    EuringLookupField(
        name="Brood Patch",
        key="brood_patch",
        type_name=TYPE_ALPHANUMERIC,
        length=1,
        required=False,
        lookup=LOOKUP_BROOD_PATCH,
    ),
    EuringField(
        name="Primary Score",
        key="primary_score",
        type_name=TYPE_INTEGER,
        length=2,
        variable_length=True,
        required=False,
    ),
    EuringField(name="Primary Moult", key="primary_moult", type_name=TYPE_ALPHANUMERIC, length=10, required=False),
    EuringFormattedField(
        name="Old Greater Coverts",
        key="old_greater_coverts",
        type_name=TYPE_ALPHANUMERIC,
        length=1,
        required=False,
        parser=parse_old_greater_coverts,
    ),
    EuringField(name="Alula", key="alula", type_name=TYPE_INTEGER, length=1, required=False),
    EuringLookupField(
        name="Carpal Covert",
        key="carpal_covert",
        type_name=TYPE_INTEGER,
        length=1,
        required=False,
        lookup=LOOKUP_CARPAL_COVERT,
    ),
    EuringLookupField(
        name="Sexing Method",
        key="sexing_method",
        type_name=TYPE_ALPHABETIC,
        length=1,
        required=False,
        lookup=LOOKUP_SEXING_METHOD,
    ),
    EuringField(name="Place Name", key="place_name", type_name=TYPE_TEXT, required=False),
    EuringField(name="Remarks", key="remarks", type_name=TYPE_TEXT, required=False),
    EuringField(name="Reference", key="reference", type_name=TYPE_TEXT, required=False),
    EuringFormattedField(
        name="Latitude", key="latitude", type_name=TYPE_NUMERIC_SIGNED, required=False, parser=parse_latitude
    ),
    EuringFormattedField(
        name="Longitude",
        key="longitude",
        type_name=TYPE_NUMERIC_SIGNED,
        required=False,
        parser=parse_longitude,
    ),
    EuringFormattedField(
        name="Current Place Code",
        key="current_place_code",
        type_name=TYPE_ALPHANUMERIC,
        length=4,
        required=False,
        parser=parse_place_code,
        lookup=lookup_place_code,
    ),
    EuringField(name="More Other Marks", key="more_other_marks", type_name=TYPE_ALPHABETIC, required=False),
]

# These are the field definitions per format as per the EURING Code Manual
EURING2020_FIELDS = EURING_FIELDS  # 64 fields
EURING2000PLUS_FIELDS = EURING_FIELDS[:60]
EURING2000_FIELDS = EURING_FIELDS[:33]
